// Ubigeo Perú — INEI
// Departamentos, Provincias y Distritos de la República del Perú

export const PAISES = [
  'PERÚ',
  'ARGENTINA',
  'BOLIVIA',
  'BRASIL',
  'CHILE',
  'COLOMBIA',
  'ECUADOR',
  'GUYANA',
  'GUYANA FRANCESA',
  'PARAGUAY',
  'SURINAM',
  'TRINIDAD Y TOBAGO',
  'URUGUAY',
  'VENEZUELA',
];

export const DEPARTAMENTOS = [
  'AMAZONAS', 'ÁNCASH', 'APURÍMAC', 'AREQUIPA', 'AYACUCHO', 'CAJAMARCA',
  'CALLAO', 'CUSCO', 'HUANCAVELICA', 'HUÁNUCO', 'ICA', 'JUNÍN',
  'LA LIBERTAD', 'LAMBAYEQUE', 'LIMA', 'LORETO', 'MADRE DE DIOS',
  'MOQUEGUA', 'PASCO', 'PIURA', 'PUNO', 'SAN MARTÍN', 'TACNA',
  'TUMBES', 'UCAYALI',
];

export const PROVINCIAS = {
  'AMAZONAS': ['CHACHAPOYAS', 'BAGUA', 'BONGARÁ', 'CONDORCANQUI', 'LUYA', 'RODRÍGUEZ DE MENDOZA', 'UTCUBAMBA'],
  'ÁNCASH': ['HUARAZ', 'AIJA', 'ANTONIO RAIMONDI', 'ASUNCIÓN', 'BOLOGNESI', 'CARHUAZ', 'CARLOS F. FITZCARRALD', 'CASMA', 'CORONGO', 'HUARI', 'HUARMEY', 'HUAYLAS', 'MARISCAL LUZURIAGA', 'OCROS', 'PALLASCA', 'POMABAMBA', 'RECUAY', 'SANTA', 'SIHUAS', 'YUNGAY'],
  'APURÍMAC': ['ABANCAY', 'ANDAHUAYLAS', 'ANTABAMBA', 'AYMARAES', 'COTABAMBAS', 'CHINCHEROS', 'GRAU'],
  'AREQUIPA': ['AREQUIPA', 'CAMANÁ', 'CARAVELÍ', 'CASTILLA', 'CAYLLOMA', 'CONDESUYOS', 'ISLAY', 'LA UNIÓN'],
  'AYACUCHO': ['HUAMANGA', 'CANGALLO', 'HUANCA SANCOS', 'HUANTA', 'LA MAR', 'LUCANAS', 'PARINACOCHAS', 'PÁUCAR DEL SARA SARA', 'SUCRE', 'VÍCTOR FAJARDO', 'VILCAS HUAMÁN'],
  'CAJAMARCA': ['CAJAMARCA', 'CAJABAMBA', 'CELENDÍN', 'CHOTA', 'CONTUMAZÁ', 'CUTERVO', 'HUALGAYOC', 'JAÉN', 'SAN IGNACIO', 'SAN MARCOS', 'SAN MIGUEL', 'SAN PABLO', 'SANTA CRUZ'],
  'CALLAO': ['CALLAO'],
  'CUSCO': ['CUSCO', 'ACOMAYO', 'ANTA', 'CALCA', 'CANAS', 'CANCHIS', 'CHUMBIVILCAS', 'ESPINAR', 'LA CONVENCIÓN', 'PARURO', 'PAUCARTAMBO', 'QUISPICANCHI', 'URUBAMBA'],
  'HUANCAVELICA': ['HUANCAVELICA', 'ACOBAMBA', 'ANGARAES', 'CASTROVIRREYNA', 'CHURCAMPA', 'HUAYTARÁ', 'TAYACAJA'],
  'HUÁNUCO': ['HUÁNUCO', 'AMBO', 'DOS DE MAYO', 'HUACAYBAMBA', 'HUAMALÍES', 'LEONCIO PRADO', 'MARAÑÓN', 'PACHITEA', 'PUERTO INCA', 'LAURICOCHA', 'YAROWILCA'],
  'ICA': ['ICA', 'CHINCHA', 'NAZCA', 'PALPA', 'PISCO'],
  'JUNÍN': ['HUANCAYO', 'CONCEPCIÓN', 'CHANCHAMAYO', 'JAUJA', 'JUNÍN', 'SATIPO', 'TARMA', 'YAULI', 'CHUPACA'],
  'LA LIBERTAD': ['TRUJILLO', 'ASCOPE', 'BOLÍVAR', 'CHEPÉN', 'GRAN CHIMÚ', 'JULCÁN', 'OTUZCO', 'PACASMAYO', 'PATAZ', 'SÁNCHEZ CARRIÓN', 'SANTIAGO DE CHUCO', 'VIRÚ'],
  'LAMBAYEQUE': ['CHICLAYO', 'FERREÑAFE', 'LAMBAYEQUE'],
  'LIMA': ['LIMA', 'BARRANCA', 'CAJATAMBO', 'CANTA', 'CAÑETE', 'HUARAL', 'HUAROCHIRÍ', 'HUAURA', 'OYÓN', 'YAUYOS'],
  'LORETO': ['MAYNAS', 'ALTO AMAZONAS', 'DATEM DEL MARAÑÓN', 'LORETO', 'MARISCAL RAMÓN CASTILLA', 'PUTUMAYO', 'REQUENA', 'UCAYALI'],
  'MADRE DE DIOS': ['TAMBOPATA', 'MANU', 'TAHUAMANU'],
  'MOQUEGUA': ['MARISCAL NIETO', 'GENERAL SÁNCHEZ CERRO', 'ILO'],
  'PASCO': ['PASCO', 'DANIEL ALCÍDES CARRIÓN', 'OXAPAMPA'],
  'PIURA': ['PIURA', 'AYABACA', 'HUANCABAMBA', 'MORROPÓN', 'PAITA', 'SULLANA', 'TALARA', 'SECHURA'],
  'PUNO': ['PUNO', 'AZÁNGARO', 'CARABAYA', 'CHUCUITO', 'EL COLLAO', 'HUANCANÉ', 'LAMPA', 'MELGAR', 'MOHO', 'SAN ANTONIO DE PUTINA', 'SAN ROMÁN', 'SANDIA', 'YUNGUYO'],
  'SAN MARTÍN': ['MOYOBAMBA', 'BELLAVISTA', 'EL DORADO', 'HUALLAGA', 'LAMAS', 'MARISCAL CÁCERES', 'PICOTA', 'RIOJA', 'SAN MARTÍN', 'TOCACHE'],
  'TACNA': ['TACNA', 'CANDARAVE', 'JORGE BASADRE', 'TARATA'],
  'TUMBES': ['TUMBES', 'CONTRALMIRANTE VILLAR', 'ZARUMILLA'],
  'UCAYALI': ['CORONEL PORTILLO', 'ATALAYA', 'PADRE ABAD', 'PURÚS'],
};

export const DISTRITOS = {
  // AMAZONAS
  'CHACHAPOYAS': ['CHACHAPOYAS', 'ASUNCIÓN', 'BALSAS', 'CHETO', 'CHILIQUÍN', 'CHUQUIBAMBA', 'GRANADA', 'HUANCAS', 'LA JALCA', 'LEIMEBAMBA', 'LEVANTO', 'MAGDALENA', 'MARISCAL CASTILLA', 'MOLINOPAMPA', 'MONTEVIDEO', 'OLLEROS', 'QUINJALCA', 'SAN FRANCISCO DE DAGUAS', 'SAN ISIDRO DE MAINO', 'SOLOCO', 'SONCHE'],
  'BAGUA': ['BAGUA', 'ARAMANGO', 'COPALLIN', 'EL PARCO', 'IMAZA', 'LA PECA'],
  'BONGARÁ': ['JUMBILLA', 'CHISQUILLA', 'CHURUJA', 'COROSHA', 'CUISPES', 'FLORIDA', 'JAZÁN', 'RECTA', 'SAN CARLOS', 'SHIPASBAMBA', 'VALERA', 'YAMBRASBAMBA'],
  'CONDORCANQUI': ['NIEVA', 'EL CENEPA', 'RÍO SANTIAGO'],
  'LUYA': ['LAMUD', 'CAMPORREDONDO', 'COCABAMBA', 'COLCAMAR', 'CONILA', 'INGUILPATA', 'LONGUITA', 'LONYA CHICO', 'LUYA', 'LUYA VIEJO', 'MARÍA', 'OCALLI', 'OCUMAL', 'PISUQUIA', 'PROVIDENCIA', 'SAN CRISTÓBAL', 'SAN JERÓNIMO', 'SAN JUAN DE LOPECANCHA', 'SANTA CATALINA', 'SANTO TOMÁS', 'TRITA'],
  'RODRÍGUEZ DE MENDOZA': ['SAN NICOLÁS', 'CHIRIMOTO', 'COCHAMAL', 'HUAMBO', 'LIMABAMBA', 'LONGAR', 'MARISCAL BENAVIDES', 'MILPUC', 'OMIA', 'SANTA ROSA', 'TOTORA', 'VISTA ALEGRE'],
  'UTCUBAMBA': ['BAGUA GRANDE', 'CAJARURO', 'CUMBA', 'EL MILAGRO', 'JAMALCA', 'LONYA GRANDE', 'YAMÓN'],

  // ÁNCASH
  'HUARAZ': ['HUARAZ', 'COCHABAMBA', 'COLCABAMBA', 'HUANCHAY', 'INDEPENDENCIA', 'JANGAS', 'LA LIBERTAD', 'LLANGANUCO', 'PAMPAS GRANDE', 'PAUCAS', 'PIRA', 'TARICA'],
  'AIJA': ['AIJA', 'CORIS', 'HUACLLÁN', 'LA MERCED', 'SUCCHA'],
  'ANTONIO RAIMONDI': ['LLAMELLÍN', 'ACZO', 'CHINGAS', 'MIRGAS', 'SAN JUAN DE RONTOY'],
  'ASUNCIÓN': ['CHACAS', 'ACOCHACA'],
  'BOLOGNESI': ['CHIQUIÁN', 'ABELARDO PARDO LEZAMETA', 'AQUIA', 'CAJACAY', 'CANIS', 'COLQUIOC', 'HUALLANCA', 'HUASTA', 'HUAYLLACAYÁN', 'LA PRIMAVERA', 'MANGAS', 'PACLLON', 'TICLLOS'],
  'CARHUAZ': ['CARHUAZ', 'ACOPAMPA', 'AMASHCA', 'ANTA', 'ATAQUERO', 'MARCARÁ', 'PAMPAS', 'SAN MIGUEL DE ACO', 'SHILLA', 'TINCO', 'YUNGAR'],
  'CARLOS F. FITZCARRALD': ['SAN LUIS', 'CATAC', 'PAMPAS CHICO', 'HUACCHIS'],
  'CASMA': ['CASMA', 'BUENA VISTA ALTA', 'COMANDANTE NOEL', 'YAUTÁN'],
  'CORONGO': ['CORONGO', 'ACO', 'BAMBAS', 'CUSCA', 'LA PAMPA', 'YANAC', 'YUPÁN'],
  'HUARI': ['HUARI', 'ANRA', 'CAJAY', 'CHAVÍN DE HUÁNTAR', 'HUACACHI', 'HUACHIS', 'HUANTAR', 'MASÍN', 'PAUCAS', 'PONTO', 'RAHUAPAMPA', 'RAPAYÁN', 'SAN MARCOS', 'SAN PEDRO DE CHAÑA'],
  'HUARMEY': ['HUARMEY', 'COCHAPETÍ', 'CULEBRAS', 'HUAYÁN', 'MALVAS'],
  'HUAYLAS': ['CARAZ', 'CHICHOCARA', 'HUALLANCA', 'HUATA', 'HUAYLAS', 'MATO', 'PAMPAROMÁS', 'PUEBLO LIBRE', 'SANTA CRUZ', 'SANTO TORIBIO', 'YURACMARCA'],
  'MARISCAL LUZURIAGA': ['PISCOBAMBA', 'CASCA', 'ELEAZAR GUZMÁN BARRÓN', 'LUCMA', 'MUSGA'],
  'OCROS': ['OCROS', 'ACAS', 'CAJAMARQUILLA', 'CARHUAPAMPA', 'COCHAS', 'CONGAS', 'LLIPA', 'SAN PEDRO', 'SANTIAGO DE CHILCAS'],
  'PALLASCA': ['CABANA', 'BOLOGNESI', 'CONCHUCOS', 'HUACASCHUQUE', 'HUANDOVAL', 'LACABAMBA', 'LLAPO', 'PALLASCA', 'PAMPAS', 'SANTA ROSA', 'TAUCA'],
  'POMABAMBA': ['POMABAMBA', 'HUAYLLAN', 'PAROBAMBA', 'QUINUABAMBA'],
  'RECUAY': ['RECUAY', 'CATAC', 'COTAPARACO', 'HUAYLLAPAMPA', 'LLACLLIN', 'MARCA', 'PÁTEC', 'TAPACOCHA', 'TICAPAMPA'],
  'SANTA': ['CHIMBOTE', 'CÁCERES DEL PERÚ', 'COISHCO', 'MACATE', 'MORO', 'NEPEÑA', 'SAMANCO', 'SANTA'],
  'SIHUAS': ['SIHUAS', 'ACOBAMBA', 'CASHAPAMPA', 'CHINGALPO', 'HUAYLLABAMBA', 'QUICHES', 'RAGASH', 'SAN JUAN', 'SICSIBAMBA'],
  'YUNGAY': ['YUNGAY', 'CASCAPARA', 'MANCOS', 'MATACOTO', 'QUILLO', 'RANRAHIRCA', 'SHUPLUY', 'YANAMA'],

  // APURÍMAC
  'ABANCAY': ['ABANCAY', 'CHACOCHE', 'CIRCA', 'CURAHUASI', 'HUANIPACA', 'LAMBRAMA', 'PICHIRHUA', 'SAN PEDRO DE CACHORA', 'TAMBURCO'],
  'ANDAHUAYLAS': ['ANDAHUAYLAS', 'ANDARAPA', 'CHIARA', 'HUANCARAMA', 'HUANCARAY', 'HUAYANA', 'KAQUIABAMBA', 'KISHUARA', 'PACOBAMBA', 'PACUCHA', 'PAMPACHIRI', 'POMACOCHA', 'SAN ANTONIO DE CACHI', 'SANTA MARÍA DE CHICMO', 'TALAVERA', 'TURPO', 'OCOBAMBA'],
  'ANTABAMBA': ['ANTABAMBA', 'EL ORO', 'HUAQUIRCA', 'JUAN ESPINOZA MEDRANO', 'OROPESA', 'PACHACONAS', 'SABAINO'],
  'AYMARAES': ['CHALHUANCA', 'CAPAYA', 'CARAYBAMBA', 'CHAPIMARCA', 'COLCABAMBA', 'COTARUSE', 'HUAYLLO', 'LUCRE', 'POCOHUANCA', 'SAÑAYCA', 'SORAYA', 'TAPAIRIHUA', 'TINTAY', 'TORAYA', 'YANACA'],
  'COTABAMBAS': ['TAMBOBAMBA', 'COYLLURQUI', 'COTABAMBAS', 'HAQUIRA', 'MARA', 'CHALLHUAHUACHO'],
  'CHINCHEROS': ['CHINCHEROS', 'ANCO-HUALLO', 'COCHARCAS', 'HUACCANA', 'OCOBAMBA', 'ONGOY', 'RANRACANCHA', 'URANMARCA'],
  'GRAU': ['CHUQUIBAMBILLA', 'CURPAHUASI', 'GAMARRA', 'HUAYLLATI', 'MAMARA', 'MICAELA BASTIDAS', 'PATAYPAMPA', 'PROGRESO', 'SAN ANTONIO', 'SANTA ROSA', 'TURPAY', 'VILCABAMBA', 'VIRUNDO'],

  // AREQUIPA
  'AREQUIPA': ['AREQUIPA', 'ALTO SELVA ALEGRE', 'CAYMA', 'CERRO COLORADO', 'CHARACATO', 'CHIGUATA', 'JACOBO HUNTER', 'JOSÉ LUIS BUSTAMANTE Y RIVERO', 'LA JOYA', 'MARIANO MELGAR', 'MIRAFLORES', 'MOLLEBAYA', 'PAUCARPATA', 'POCSI', 'POLOBAYA', 'QUEQUEÑA', 'SACHACA', 'SABANDIA', 'SOCABAYA', 'TIABAYA', 'UCHUMAYO', 'VITOR', 'YANAHUARA', 'YARABAMBA', 'YURA'],
  'CAMANÁ': ['CAMANÁ', 'JOSÉ MARÍA QUIMPER', 'MARIANO NICOLÁS VALCÁRCEL', 'MARISCAL CÁCERES', 'NICOLÁS DE PIÉROLA', 'OCOÑA', 'QUILCA', 'SAMUEL PASTOR'],
  'CARAVELÍ': ['CARAVELÍ', 'ACARÍ', 'ATICO', 'ATIQUIPA', 'BELLA UNIÓN', 'CAHUACHO', 'CHALA', 'CHAPARRA', 'JAQUI', 'LOMAS', 'QUICACHA', 'YAUCA'],
  'CASTILLA': ['APLAO', 'ANDAGUA', 'AYO', 'CHACHAS', 'CHILCAYMARCA', 'CHOCO', 'HUANCARQUI', 'MACHAGUAY', 'ORCOPAMPA', 'PAMPACOLCA', 'TIPÁN', 'VIRACO'],
  'CAYLLOMA': ['CHIVAY', 'ACHOMA', 'CABANACONDE', 'CALLALLI', 'CAYLLOMA', 'COPORAQUE', 'HUAMBO', 'HUANCA', 'ICHUPAMPA', 'LARI', 'LLUTA', 'MACA', 'MADRIGAL', 'SAN ANTONIO DE CHUCA', 'SIBAYO', 'TAPAY', 'TISCO', 'TUTI', 'YANQUE', 'MAJES'],
  'CONDESUYOS': ['CHUQUIBAMBA', 'ANDARAY', 'CAYARANI', 'CHICHAS', 'IRAY', 'RÍO GRANDE', 'SALAMANCA', 'YANAQUIHUA'],
  'ISLAY': ['MOLLENDO', 'COCACHACRA', 'DEAN VALDIVIA', 'ISLAY', 'MEJÍA', 'PUNTA DE BOMBÓN'],
  'LA UNIÓN': ['COTAHUASI', 'ALCA', 'CHARCANA', 'HUAYNACOTAS', 'PAMPAMARCA', 'PUYCA', 'QUECHUALLA', 'SAYLA', 'TAURIA', 'TOMEPAMPA', 'TORO'],

  // AYACUCHO
  'HUAMANGA': ['AYACUCHO', 'ACOCRO', 'ACOS VINCHOS', 'CARMEN ALTO', 'CHIARA', 'JESÚS NAZARENO', 'OCROS', 'PACAYCASA', 'QUINUA', 'SAN JOSÉ DE TICLLAS', 'SAN JUAN BAUTISTA', 'SANTIAGO DE PISCHA', 'SOCOS', 'TAMBILLO', 'VINCHOS'],
  'CANGALLO': ['CANGALLO', 'CHUSCHI', 'LOS MOROCHUCOS', 'MARÍA PARADO DE BELLIDO', 'PARAS', 'TOTOS'],
  'HUANCA SANCOS': ['SANCOS', 'CARAPO', 'SACSAMARCA', 'SANTIAGO DE LUCANAMARCA'],
  'HUANTA': ['HUANTA', 'AYAHUANCO', 'HUAMANGUILLA', 'IGUAÍN', 'LURICOCHA', 'SANTILLANA', 'SIVIA', 'LLOCHEGUA', 'CANAYRE', 'UCHURACCAY'],
  'LA MAR': ['SAN MIGUEL', 'ANCO', 'AYNA', 'CHILCAS', 'CHUNGUI', 'LUIS CARRANZA', 'SANTA ROSA', 'TAMBO', 'SAMUGARI', 'ANCHIHUAY'],
  'LUCANAS': ['PUQUIO', 'AUCARA', 'CABANA', 'CARMEN SALCEDO', 'CHAVIÑA', 'CHIPAO', 'HUAC-HUAS', 'LARAMATE', 'LEONCIO PRADO', 'LLAUTA', 'LUCANAS', 'OCAÑA', 'OTOCA', 'SAISA', 'SAN CRISTÓBAL', 'SAN JUAN', 'SAN PEDRO', 'SAN PEDRO DE PALCO', 'SANCOS', 'SANTA LUCÍA'],
  'PARINACOCHAS': ['CORACORA', 'CHUMPI', 'CORONEL CASTAÑEDA', 'PACAPAUSA', 'PUYUSCA', 'SAN FRANCISCO DE RAVACAYCO', 'UPAHUACHO'],
  'PÁUCAR DEL SARA SARA': ['PAUSA', 'COLTA', 'CORCULLA', 'LAMPA', 'MARCABAMBA', 'OYOLO', 'PARARCA', 'SAN JAVIER DE ALPABAMBA', 'SARA SARA'],
  'SUCRE': ['QUEROBAMBA', 'BELÉN', 'CHALCOS', 'CHILCAYOC', 'HUACAÑA', 'MORCOLLA', 'PAICO', 'SAN SALVADOR DE QUIJE', 'SANTIAGO DE PAUCARAY', 'SORAS'],
  'VÍCTOR FAJARDO': ['HUANCAPI', 'ALCAMENCA', 'APONGO', 'ASQUIPATA', 'CANARIA', 'CAYARA', 'COLCA', 'HUAMANQUIQUIA', 'HUANCARAYLLA', 'HUAYA', 'SARHUA', 'VILCANCHOS'],
  'VILCAS HUAMÁN': ['VILCAS HUAMÁN', 'ACCOMARCA', 'CARHUANCA', 'CONCEPCIÓN', 'HUAMBALPA', 'INDEPENDENCIA', 'SAURAMA', 'VISCHONGO'],

  // CAJAMARCA
  'CAJAMARCA': ['CAJAMARCA', 'ASUNCIÓN', 'CHETILLA', 'COSPAN', 'ENCAÑADA', 'JESÚS', 'LLACANORA', 'LOS BAÑOS DEL INCA', 'MAGDALENA', 'NAMORA', 'SAN JUAN'],
  'CAJABAMBA': ['CAJABAMBA', 'CACHACHI', 'CONDEBAMBA', 'SITACOCHA'],
  'CELENDÍN': ['CELENDÍN', 'CHUMUCH', 'CORTEGANA', 'HUASMIN', 'JORGE CHÁVEZ', 'JOSÉ GÁLVEZ', 'MIGUEL IGLESIAS', 'OXAMARCA', 'SOROCHUCO', 'SUCRE', 'UTCO', 'LA LIBERTAD DE PALLÁN'],
  'CHOTA': ['CHOTA', 'ANGUÍA', 'CHADIN', 'CHIGUIRIP', 'CHIMBAN', 'CHOROPAMPA', 'COCHABAMBA', 'CONCHAN', 'HUAMBOS', 'LAJAS', 'LLAMA', 'MIRACOSTA', 'PACCHA', 'QUEROCOTO', 'TACABAMBA', 'TOCMOCHE', 'CHALAMARCA'],
  'CONTUMAZÁ': ['CONTUMAZÁ', 'CHILETE', 'CUPISNIQUE', 'GUZMANGO', 'SAN BENITO', 'SANTA CRUZ DE TOLEDO', 'TANTARICA', 'YONÁN'],
  'CUTERVO': ['CUTERVO', 'CALLAYUC', 'CUJILLO', 'LA RAMADA', 'PIMPINGOS', 'QUEROCOTILLO', 'SAN ANDRÉS DE CUTERVO', 'SAN JUAN DE CUTERVO', 'SAN LUIS DE LUCMA', 'SANTA CRUZ', 'SANTO TOMAS', 'SOCOTA', 'TORIBIO CASANOVA'],
  'HUALGAYOC': ['BAMBAMARCA', 'CHUGUR', 'HUALGAYOC'],
  'JAÉN': ['JAÉN', 'BELLAVISTA', 'CHONTALI', 'COLASAY', 'HUABAL', 'LAS PIRIAS', 'POMAHUACA', 'PUCARÁ', 'SALLIQUE', 'SAN FELIPE', 'SAN JOSÉ DEL ALTO', 'SANTA ROSA'],
  'SAN IGNACIO': ['SAN IGNACIO', 'CHIRINOS', 'HUARANGO', 'LA COIPA', 'NAMBALLE', 'SAN JOSÉ DE LOURDES', 'TABACONAS'],
  'SAN MARCOS': ['PEDRO GÁLVEZ', 'CHANCAY', 'EDUARDO VILLANUEVA', 'GREGORIO PITA', 'ICHOCAN', 'JOSÉ MANUEL QUIROZ', 'JOSÉ SABOGAL'],
  'SAN MIGUEL': ['SAN MIGUEL', 'BOLÍVAR', 'CALQUIS', 'CATILLUC', 'EL PRADO', 'LA FLORIDA', 'LLAPA', 'NANCHOC', 'NIEPOS', 'SAN GREGORIO', 'SAN SILVESTRE DE COCHAN', 'TONGOD', 'UNIÓN AGUA BLANCA'],
  'SAN PABLO': ['SAN PABLO', 'SAN BERNARDINO', 'SAN LUIS', 'TUMBADÉN'],
  'SANTA CRUZ': ['SANTA CRUZ', 'ANDABAMBA', 'CATACHE', 'CHANCAYBAÑOS', 'LA ESPERANZA', 'NINABAMBA', 'PULAN', 'SAUCEPAMPA', 'SEXI', 'UTICYACU', 'YAUYUCÁN'],

  // CALLAO
  'CALLAO': ['CALLAO', 'BELLAVISTA', 'CARMEN DE LA LEGUA REYNOSO', 'LA PERLA', 'LA PUNTA', 'MI PERÚ', 'VENTANILLA'],

  // CUSCO
  'CUSCO': ['CUSCO', 'CCORCA', 'POROY', 'SAN JERÓNIMO', 'SAN SEBASTIÁN', 'SANTIAGO', 'SAYLLA', 'WANCHAQ'],
  'ACOMAYO': ['ACOMAYO', 'ACOPIA', 'ACOS', 'MOSOC LLACTA', 'POMACANCHI', 'RONDOCAN', 'SANGARARÁ'],
  'ANTA': ['ANTA', 'ANCAHUASI', 'CACHIMAYO', 'CHINCHAYPUJIO', 'HUAROCONDO', 'LIMATAMBO', 'MOLLEPATA', 'PUCYURA', 'ZURITE'],
  'CALCA': ['CALCA', 'COYA', 'LAMAY', 'LARES', 'PISAC', 'SAN SALVADOR', 'TARAY', 'YANATILE'],
  'CANAS': ['YANAOCA', 'CHECCA', 'KUNTURKANKI', 'LANGUI', 'LAYO', 'PAMPAMARCA', 'QUEHUE', 'TUPAC AMARU'],
  'CANCHIS': ['SICUANI', 'CHECACUPE', 'COMBAPATA', 'MARANGANÍ', 'PITUMARCA', 'SAN PABLO', 'SAN PEDRO', 'TINTA'],
  'CHUMBIVILCAS': ['SANTO TOMÁS', 'CAPACMARCA', 'CHAMACA', 'COLQUEMARCA', 'LIVITACA', 'LLUSCO', 'QUIÑOTA', 'VELILLE'],
  'ESPINAR': ['ESPINAR', 'ALTO PICHIGUA', 'COPORAQUE', 'OCCORURO', 'PALLPATA', 'PICHIGUA', 'SUYCKUTAMBO', 'CONDOROMA'],
  'LA CONVENCIÓN': ['SANTA ANA', 'ECHARATE', 'HUAYOPATA', 'KIMBIRI', 'KOSÑIPATA', 'MARANURA', 'MEGANTONI', 'OCOBAMBA', 'QUELLOUNO', 'QUIMBIRI', 'SANTA TERESA', 'VILCABAMBA', 'PICHARI'],
  'PARURO': ['PARURO', 'ACCHA', 'CCAPI', 'COLCHA', 'HUANOQUITE', 'OMACHA', 'PACCARITAMBO', 'PILLPINTO', 'YAURISQUE'],
  'PAUCARTAMBO': ['PAUCARTAMBO', 'CAICAY', 'CHALLABAMBA', 'COLQUEPATA', 'HUANCARANI', 'KOSÑIPATA'],
  'QUISPICANCHI': ['URCOS', 'ANDAHUAYLILLAS', 'CAMANTI', 'CCARHUAYO', 'CCATCA', 'CUSIPATA', 'HUARO', 'LUCRE', 'MARCAPATA', 'OCONGATE', 'OROPESA', 'QUIQUIJANA'],
  'URUBAMBA': ['URUBAMBA', 'CHINCHERO', 'HUAYLLABAMBA', 'MACHUPICCHU', 'MARAS', 'OLLANTAYTAMBO', 'YUCAY'],

  // HUANCAVELICA
  'HUANCAVELICA': ['HUANCAVELICA', 'ACOBAMBILLA', 'ACORIA', 'CONAYCA', 'CUENCA', 'HUACHOCOLPA', 'HUAYLLAHUARA', 'IZCUCHACA', 'LARIA', 'MANTA', 'MARISCAL CÁCERES', 'MOYA', 'NUEVO OCCORO', 'PALCA', 'PILCHACA', 'VILCA', 'YAULI'],
  'ACOBAMBA': ['ACOBAMBA', 'ANDABAMBA', 'ANTA', 'CAJA', 'MARCAS', 'PAUCARA', 'POMACOCHA', 'ROSARIO'],
  'ANGARAES': ['LIRCAY', 'ANCHONGA', 'CALLANMARCA', 'CCOCHACCASA', 'CHINCHO', 'CONGALLA', 'HUANCA-HUANCA', 'HUAYLLAY GRANDE', 'JULCAMARCA', 'SAN ANTONIO DE ANTAPARCO', 'SANTO TOMAS DE PATA', 'SECCLLA'],
  'CASTROVIRREYNA': ['CASTROVIRREYNA', 'ARMA', 'AURAHUA', 'CAPILLAS', 'CHUPAMARCA', 'COCAS', 'HUACHOS', 'HUAMATAMBO', 'MOLLEPAMPA', 'SAN JUAN', 'SANTA ANA', 'TANTARÁ', 'TICRAPO'],
  'CHURCAMPA': ['CHURCAMPA', 'ANCO', 'CHINCHIHUASI', 'EL CARMEN', 'LA MERCED', 'LOCROJA', 'PAUCARBAMBA', 'SAN MIGUEL DE MAYOCC', 'SAN PEDRO DE CORIS'],
  'HUAYTARÁ': ['HUAYTARÁ', 'AYAVÍ', 'CÓRDOVA', 'HUAYACUNDO ARMA', 'LARAMARCA', 'OCOYO', 'PILPICHACA', 'QUERCO', 'SAN ANTONIO DE CUSICANCHA', 'SANTO DOMINGO DE CAPILLAS', 'TAMBO'],
  'TAYACAJA': ['PAMPAS', 'ACOSTAMBO', 'ACRAQUIA', 'AHUAYCHA', 'COLCABAMBA', 'DANIEL HERNÁNDEZ', 'HUACHOCOLPA', 'HUARIBAMBA', 'ÑAHUIMPUQUIO', 'PAZOS', 'PICHOS', 'QUISHUAR', 'SALCABAMBA', 'SALCAHUASI', 'SAN MARCOS DE ROCCHAC', 'SURCUBAMBA', 'TINTAY PUNCU'],

  // HUÁNUCO
  'HUÁNUCO': ['HUÁNUCO', 'AMARILIS', 'CHURUBAMBA', 'MARGOS', 'QUISQUI', 'SAN FRANCISCO DE CAYRÁN', 'SAN PEDRO DE CHAULÁN', 'SANTA MARÍA DEL VALLE', 'YARUMAYO', 'PILLCO MARCA'],
  'AMBO': ['AMBO', 'CAYNA', 'COLPAS', 'CONCHAMARCA', 'HUÁCAR', 'SAN FRANCISCO', 'SAN RAFAEL', 'TOMAY KICHWA'],
  'DOS DE MAYO': ['LA UNIÓN', 'CHUQUIS', 'MARÍAS', 'PACHAS', 'QUIVILLA', 'RIPÁN', 'SHUNQUI', 'SILLAPATA', 'YANAS'],
  'HUACAYBAMBA': ['HUACAYBAMBA', 'CANCHABAMBA', 'COCHABAMBA', 'PINRA'],
  'HUAMALÍES': ['LLATA', 'ARANCAY', 'CHAVÍN DE PARIARCA', 'JACAS GRANDE', 'JIRCÁN', 'MIRAFLORES', 'MONZÓN', 'PUNCHAO', 'PUÑOS', 'SINGA', 'TANTAMAYO'],
  'LEONCIO PRADO': ['TINGO MARÍA', 'DANIEL ALOMÍA ROBLES', 'HERMÍLIO VALDIZÁN', 'JOSÉ CRESPO Y CASTILLO', 'LUYANDO', 'MARIANO DÁMASO BERAÚN'],
  'MARAÑÓN': ['HUACRACHUCO', 'CHOLÓN', 'SAN BUENAVENTURA'],
  'PACHITEA': ['PANAO', 'CHAGLLA', 'MOLINO', 'UMARI'],
  'PUERTO INCA': ['PUERTO INCA', 'CODO DEL POZUZO', 'HONORIA', 'TOURNAVISTA', 'YUYAPICHIS'],
  'LAURICOCHA': ['JESÚS', 'BAÑOS', 'JIVIA', 'QUEROPALCA', 'RONDOS', 'SAN FRANCISCO DE ASÍS', 'SAN MIGUEL DE CAURI'],
  'YAROWILCA': ['CHAVINILLO', 'CAHUAC', 'CHACABAMBA', 'APARICIO POMARES', 'JACAS CHICO', 'OBAS', 'PAMPAMARCA', 'CHORAS'],

  // ICA
  'ICA': ['ICA', 'LA TINGUIÑA', 'LOS AQUIJES', 'OCUCAJE', 'PACHACUTEC', 'PARCONA', 'PUEBLO NUEVO', 'SALAS', 'SAN JOSÉ DE LOS MOLINOS', 'SAN JUAN BAUTISTA', 'SANTIAGO', 'SUBTANJALLA', 'TATE', 'YAUCA DEL ROSARIO'],
  'CHINCHA': ['CHINCHA ALTA', 'ALTO LARÁN', 'CHAVÍN', 'CHINCHA BAJA', 'EL CARMEN', 'GROCIO PRADO', 'PUEBLO NUEVO', 'SUNAMPE', 'TAMBO DE MORA'],
  'NAZCA': ['NAZCA', 'CHANGUILLO', 'EL INGENIO', 'MARCONA', 'VISTA ALEGRE'],
  'PALPA': ['PALPA', 'LLIPATA', 'RÍO GRANDE', 'SANTA CRUZ', 'TIBILLO'],
  'PISCO': ['PISCO', 'HUANCANO', 'HUMAY', 'INDEPENDENCIA', 'PARACAS', 'SAN ANDRÉS', 'SAN CLEMENTE', 'TÚPAC AMARU INCA'],

  // JUNÍN
  'HUANCAYO': ['HUANCAYO', 'CARHUACALLANGA', 'CHACAPAMPA', 'CHICCHE', 'CHILCA', 'CHONGOS BAJO', 'CHUPURO', 'COLCA', 'CULLHUAS', 'EL TAMBO', 'HUACRAPUQUIO', 'HUALHUAS', 'HUANCÁN', 'HUASICANCHA', 'HUAYUCACHI', 'INGENIO', 'PARIAHUANCA', 'PILCOMAYO', 'PUCARÁ', 'QUILCAS', 'SAN AGUSTÍN', 'SAN JERÓNIMO DE TUNÁN', 'SAÑO', 'SAPALLANGA', 'SICAYA', 'SANTO DOMINGO DE ACOBAMBA', 'VIQUES'],
  'CONCEPCIÓN': ['CONCEPCIÓN', 'ACO', 'ANDAMARCA', 'CHAMBARA', 'COCHAS', 'COMAS', 'HEROÍNAS TOLEDO', 'MANZANARES', 'MARISCAL CASTILLA', 'MATAHUASI', 'MITO', 'NUEVE DE JULIO', 'ORCOTUNA', 'SAN JOSÉ DE QUERO', 'SANTA ROSA DE OCOPA'],
  'CHANCHAMAYO': ['LA MERCED', 'CHANCHAMAYO', 'PERENÉ', 'PICHANAQUI', 'SAN LUIS DE SHUARO', 'SAN RAMÓN', 'VITOC'],
  'JAUJA': ['JAUJA', 'ACOLLA', 'ACI', 'APATA', 'ATAURA', 'CANCHAYLLO', 'CURICACA', 'EL MANTARO', 'HUAMALI', 'HUARIPAMPA', 'HUERTAS', 'JANJAILLO', 'JULCÁN', 'LEONOR ORDÓÑEZ', 'LLOCLLAPAMPA', 'MARCO', 'MASMA', 'MASMA CHICCHE', 'MOLINOS', 'MONOBAMBA', 'MUQUI', 'MUQUIYAUYO', 'PACA', 'PACCHA', 'PANCÁN', 'PARCO', 'POMACANCHA', 'RICRÁN', 'SAN LORENZO', 'SAN PEDRO DE CHUNAN', 'SAUSA', 'SINCOS', 'TUNANMARCA', 'YAULI', 'YAUYOS'],
  'JUNÍN': ['JUNÍN', 'CARHUAMAYO', 'ONDORES', 'ULCUMAYO'],
  'SATIPO': ['SATIPO', 'COVIRIALI', 'LLAYLLA', 'MAZAMARI', 'PAMPA HERMOSA', 'PANGOA', 'RÍO NEGRO', 'RÍO TAMBO', 'VIZCATAN DEL ENE'],
  'TARMA': ['TARMA', 'ACOBAMBA', 'HUARICOLCA', 'HUASAHUASI', 'LA UNIÓN', 'PALCA', 'PALCAMAYO', 'SAN PEDRO DE CAJAS', 'TAPO'],
  'YAULI': ['LA OROYA', 'CHACAPALPA', 'HUAY-HUAY', 'MARCAPOMACOCHA', 'MOROCOCHA', 'PACCHA', 'SANTA BÁRBARA DE CARHUACAYÁN', 'SANTA ROSA DE SACCO', 'SUITUCANCHA', 'YAULI'],
  'CHUPACA': ['CHUPACA', 'AHUAC', 'CHONGOS ALTO', 'HUACHAC', 'HUAMANCACA CHICO', 'SAN JUAN DE JARPA', 'TRES DE DICIEMBRE', 'YANACANCHA'],

  // LA LIBERTAD
  'TRUJILLO': ['TRUJILLO', 'EL PORVENIR', 'FLORENCIA DE MORA', 'HUANCHACO', 'LA ESPERANZA', 'LAREDO', 'MOCHE', 'MOCHE', 'POROTO', 'SALAVERRY', 'SIMBAL', 'VÍCTOR LARCO HERRERA'],
  'ASCOPE': ['ASCOPE', 'CHICAMA', 'CHOCOPE', 'GUADALUPITO', 'LICAPA', 'MAGDALENA DE CAO', 'PAIJÁN', 'RÁZURI', 'SANTIAGO DE CAO'],
  'BOLÍVAR': ['BOLÍVAR', 'BAMBAMARCA', 'CONDORMARCA', 'LONGOTEA', 'UCHUMARCA', 'UCUNCHA'],
  'CHEPÉN': ['CHEPÉN', 'PACANGA', 'PUEBLO NUEVO'],
  'GRAN CHIMÚ': ['CASCAS', 'LUCMA', 'MARMOT', 'SAYAPULLO'],
  'JULCÁN': ['JULCÁN', 'CALAMARCA', 'CARABAMBA', 'HUASO'],
  'OTUZCO': ['OTUZCO', 'AGALLPAMPA', 'CHARAT', 'HUARANCHAL', 'LA CUESTA', 'MACHE', 'PARANDAY', 'SALPO', 'SINSICAP', 'USQUIL'],
  'PACASMAYO': ['SAN PEDRO DE LLOC', 'GUADALUPE', 'JEQUETEPEQUE', 'PACASMAYO', 'SAN JOSÉ'],
  'PATAZ': ['TAYABAMBA', 'BULDIBUYO', 'CHILLIA', 'HUAYLILLAS', 'HUANCASPATA', 'HUAYO', 'ONGÓN', 'PARCOY', 'PATAZ', 'PÍAS', 'SANTIAGO DE CHALLAS', 'TAURIJA', 'URPAY'],
  'SÁNCHEZ CARRIÓN': ['HUAMACHUCO', 'CHUGAY', 'COCHORCO', 'CURGOS', 'MARCABAL', 'SANAGORÁN', 'SARÍN', 'SARTIMBAMBA'],
  'SANTIAGO DE CHUCO': ['SANTIAGO DE CHUCO', 'ANGASMARCA', 'CACHICADÁN', 'MOLLEBAMBA', 'MOLLEPATA', 'QUIRUVILCA', 'SANTA CRUZ DE CHUCA', 'SITABAMBA'],
  'VIRÚ': ['VIRÚ', 'CHAO', 'GUADALUPITO'],

  // LAMBAYEQUE
  'CHICLAYO': ['CHICLAYO', 'CHONGOYAPE', 'ETEN', 'ETEN PUERTO', 'JOSÉ LEONARDO ORTIZ', 'LA VICTORIA', 'LAGUNAS', 'MONSEFÚ', 'NUEVA ARICA', 'OYOTÚN', 'PICSI', 'PIMENTEL', 'REQUE', 'SANTA ROSA', 'SAÑA', 'CAYALTÍ', 'PÁTAPO', 'POMALCA', 'PUCALÁ', 'TUMÁN'],
  'FERREÑAFE': ['FERREÑAFE', 'CAÑARIS', 'INCAHUASI', 'MANUEL ANTONIO MESONES MURO', 'PITIPO', 'PUEBLO NUEVO'],
  'LAMBAYEQUE': ['LAMBAYEQUE', 'CHÓCHOPE', 'ILLIMO', 'JAYANCA', 'MOCHUMÍ', 'MÓRROPE', 'MOTUPE', 'OLMOS', 'PACORA', 'SALAS', 'SAN JOSÉ', 'TÚCUME'],

  // LIMA
  'LIMA': ['LIMA', 'ANCÓN', 'ATE', 'BARRANCO', 'BREÑA', 'CARABAYLLO', 'CHACLACAYO', 'CHORRILLOS', 'CIENEGUILLA', 'COMAS', 'EL AGUSTINO', 'INDEPENDENCIA', 'JESÚS MARÍA', 'LA MOLINA', 'LA VICTORIA', 'LINCE', 'LOS OLIVOS', 'LURIGANCHO', 'LURÍN', 'MAGDALENA DEL MAR', 'MAGDALENA VIEJA', 'MIRAFLORES', 'PACHACÁMAC', 'PUCUSANA', 'PUNTA HERMOSA', 'PUNTA NEGRA', 'RÍMAC', 'SAN BARTOLO', 'SAN BORJA', 'SAN ISIDRO', 'SAN JUAN DE LURIGANCHO', 'SAN JUAN DE MIRAFLORES', 'SAN LUIS', 'SAN MARTÍN DE PORRES', 'SAN MIGUEL', 'SANTA ANITA', 'SANTA MARÍA DEL MAR', 'SANTA ROSA', 'SANTIAGO DE SURCO', 'SURQUILLO', 'VILLA EL SALVADOR', 'VILLA MARÍA DEL TRIUNFO'],
  'BARRANCA': ['BARRANCA', 'ÁMBAR', 'CHASQUITAMBO', 'MIRAS', 'PUERTO SUPE', 'SUPE'],
  'CAJATAMBO': ['CAJATAMBO', 'COPA', 'GORGOR', 'HUANCAPÓN', 'MANAS'],
  'CANTA': ['CANTA', 'ARAHUAY', 'HUAMANTANGA', 'HUAROS', 'LACHAQUI', 'SAN BUENAVENTURA', 'SANTA ROSA DE QUIVES'],
  'CAÑETE': ['SAN VICENTE DE CAÑETE', 'ASIA', 'CALANGO', 'CERRO AZUL', 'CHILCA', 'COAYLLO', 'IMPERIAL', 'LUNAHUANÁ', 'MALA', 'NUEVO IMPERIAL', 'PACARÁN', 'QUILMANÁ', 'SAN ANTONIO', 'SAN LUIS', 'SANTA CRUZ DE FLORES', 'ZÚÑIGA'],
  'HUARAL': ['HUARAL', 'ATAVILLOS ALTO', 'ATAVILLOS BAJO', 'AUCALLAMA', 'CHANCAY', 'IHUARI', 'LAMPIÁN', 'PACARAOS', 'SAN MIGUEL DE ACOS', 'SANTA CRUZ DE ANDAMARCA', 'SUMBILCA', 'VÉGUETA'],
  'HUAROCHIRÍ': ['MATUCANA', 'ANTIOQUÍA', 'CALLAHUANCA', 'CARAMPOMA', 'CHICLA', 'CUENCA', 'HUACHUPAMPA', 'HUANZA', 'HUAROCHIRÍ', 'LAHUAYTAMBO', 'LANGA', 'LARAOS', 'MARIATANA', 'RICARDO PALMA', 'SAN ANDRÉS DE TUPICOCHA', 'SAN ANTONIO', 'SAN DAMIÁN', 'SAN JUAN DE IRIS', 'SAN MATEO', 'SAN MATEO DE OTAO', 'SAN PEDRO DE CASTA', 'SAN PEDRO DE HUANCAYRE', 'SANGALLAYA', 'SANTA CRUZ DE COCACHACRA', 'SANTA EULALIA', 'SANTIAGO DE ANCHUCAYA', 'SANTIAGO DE TUNA', 'SANTO DOMINGO DE LOS OLLEROS', 'SURCO'],
  'HUAURA': ['HUACHO', 'AMBAR', 'CALETA DE CARQUÍN', 'CHECRAS', 'HUALMAY', 'HUAURA', 'LEONCIO PRADO', 'PACCHO', 'SANTA LEONOR', 'SANTA MARÍA', 'SAYÁN', 'VÉGUETA'],
  'OYÓN': ['OYÓN', 'ANDAJES', 'CAUJUL', 'COCHAMARCA', 'NAVÁN', 'PACHANGARA'],
  'YAUYOS': ['YAUYOS', 'ALIS', 'ALLAUCA', 'AYAUCA', 'AYAVIRI', 'AZÁNGARO', 'CACRA', 'CARANIA', 'CATAHUASI', 'CHOCOS', 'COCHAS', 'COLONIA', 'HONGOS', 'HUAMPARÁ', 'HUANCAYA', 'HUANGÁSCAR', 'HUANTÁN', 'HUAÑEC', 'LARAOS', 'LINCHA', 'MADEAN', 'MIRAFLORES', 'OMAS', 'PUTINZA', 'QUINCHES', 'QUINOCAY', 'SAN JOAQUÍN', 'SIRIA', 'TAURIPAMPA', 'TOMAS', 'TUPE', 'VIÑAC', 'VITIS'],

  // LORETO
  'MAYNAS': ['IQUITOS', 'ALTO NANAY', 'FERNANDO LORES', 'INDIANA', 'LAS AMAZONAS', 'MAZÁN', 'NAPO', 'PUNCHANA', 'BELÉN', 'SAN JUAN BAUTISTA', 'PUTUMAYO'],
  'ALTO AMAZONAS': ['YURIMAGUAS', 'BALSAPUERTO', 'JEBEROS', 'LAGUNAS', 'SANTA CRUZ', 'TENIENTE CÉSAR LÓPEZ ROJAS'],
  'DATEM DEL MARAÑÓN': ['SAN LORENZO', 'ANDOAS', 'BARRANCA', 'CAHUAPANAS', 'MANSERICHE', 'MORONA', 'PASTAZA'],
  'LORETO': ['NAUTA', 'PARINARI', 'TIGRE', 'TROMPETEROS', 'URARINAS'],
  'MARISCAL RAMÓN CASTILLA': ['RAMÓN CASTILLA', 'PEBAS', 'SAN PABLO', 'YAQUERANA'],
  'PUTUMAYO': ['SAN ANTONIO DEL ESTRECHO', 'HUAPAPA', 'ROSA PANDURO', 'TENIENTE MANUEL CLAVERO', 'YAGUAS'],
  'REQUENA': ['REQUENA', 'ALTO TAPICHE', 'CAPELO', 'EMILIO SAN MARTÍN', 'MAQUIA', 'PUINAHUA', 'SAQUENA', 'SOPLIN', 'TAPICHE', 'JENARO HERRERA', 'YAQUERANA'],
  'UCAYALI': ['CONTAMANA', 'INAHUAYA', 'PADRE MÁRQUEZ', 'PAMPA HERMOSA', 'SARAYACU', 'VARGAS GUERRA'],

  // MADRE DE DIOS
  'TAMBOPATA': ['PUERTO MALDONADO', 'INAMBARI', 'LAS PIEDRAS', 'LABERINTO'],
  'MANU': ['MANU', 'FITZCARRALD', 'MADRE DE DIOS', 'URRELO'],
  'TAHUAMANU': ['IÑAPARI', 'IBERIA', 'TAHUAMANU'],

  // MOQUEGUA
  'MARISCAL NIETO': ['MOQUEGUA', 'CARUMAS', 'CUCHUMBAYA', 'SAMEGUA', 'SAN CRISTÓBAL', 'TORATA'],
  'GENERAL SÁNCHEZ CERRO': ['OMATE', 'CHOJATA', 'COALAQUE', 'ICHUÑA', 'LA CAPILLA', 'LLOQUE', 'MATALAQUE', 'PUQUINA', 'QUINISTAQUILLAS', 'UBINAS', 'YUNGA'],
  'ILO': ['ILO', 'EL ALGARROBAL', 'PACOCHA'],

  // PASCO
  'PASCO': ['CHAUPIMARCA', 'HUACHÓN', 'HUARIACA', 'HUAYLLAY', 'NINACACA', 'PALLANCHACRA', 'PAUCARTAMBO', 'SAN FRANCISCO DE ASÍS DE YARUSYACÁN', 'SIMÓN BOLÍVAR', 'TICLACAYÁN', 'TINYAHUARCO', 'VICCO', 'YANACANCHA'],
  'DANIEL ALCÍDES CARRIÓN': ['YANAHUANCA', 'CHACAYÁN', 'GOYLLARISQUIZGA', 'PAUCAR', 'SAN PEDRO DE PILLAO', 'SANTA ANA DE TUSI', 'TAPUC', 'VILCABAMBA'],
  'OXAPAMPA': ['OXAPAMPA', 'CHONTABAMBA', 'HUANCABAMBA', 'PALAZ', 'POZUZO', 'PUERTO BERMÚDEZ', 'VILLA RICA'],

  // PIURA
  'PIURA': ['PIURA', 'CASTILLA', 'CATACAOS', 'CURA MORÍ', 'EL TALLÁN', 'LA ARENA', 'LA UNIÓN', 'LAS LOMAS', 'TAMBOGRANDE', 'VEINTISEIS DE OCTUBRE'],
  'AYABACA': ['AYABACA', 'FRIAS', 'JILILI', 'LAGUNAS', 'MONTERO', 'PACAIPAMPA', 'PAIMAS', 'SAPILLICA', 'SICCHEZ', 'SUYO'],
  'HUANCABAMBA': ['HUANCABAMBA', 'CANCHAQUE', 'EL CARMEN DE LA FRONTERA', 'HUARMACA', 'LALAQUIZ', 'SAN MIGUEL DEL FAIQUE', 'SONDOR', 'SONDORILLO'],
  'MORROPÓN': ['CHULUCANAS', 'BUENOS AIRES', 'CHALACO', 'LA MATANZA', 'MORROPÓN', 'SALITRAL', 'SAN JUAN DE BIGOTE', 'SANTA CATALINA DE MOSSA', 'SANTO DOMINGO', 'YAMANGO'],
  'PAITA': ['PAITA', 'AMOTAPE', 'ARENAL', 'COLÁN', 'LA HUACA', 'TAMARINDO', 'VICHAYAL'],
  'SULLANA': ['SULLANA', 'BELLAVISTA', 'IGNACIO ESCUDERO', 'LANCONES', 'MARCAVELICA', 'MIGUEL CHECA', 'QUERECOTILLO', 'SALITRAL'],
  'TALARA': ['PARIÑAS', 'EL ALTO', 'LA BREA', 'LOBITOS', 'LOS ÓRGANOS', 'MÁNCORA'],
  'SECHURA': ['SECHURA', 'BELLAVISTA DE LA UNIÓN', 'BERNAL', 'CRISTO NOS VALGA', 'RINCONADA LLICUAR', 'VICE'],

  // PUNO
  'PUNO': ['PUNO', 'ACORA', 'AMANTANI', 'ATUNCOLLA', 'CAPACHICA', 'CHUCUITO', 'COATA', 'HUATA', 'MAÑAZO', 'PAUCARCOLLA', 'PICHACANI', 'PLATERÍA', 'SAN ANTONIO', 'TIQUILLACA', 'VILQUE'],
  'AZÁNGARO': ['AZÁNGARO', 'ACHAYA', 'ARAPA', 'ASILLO', 'CAMINACA', 'CHUPA', 'JOSÉ DOMINGO CHOQUEHUANCA', 'MUÑANI', 'POTONI', 'SAMÁN', 'SAN ANTÓN', 'SAN JOSÉ', 'SAN JUAN DE SALINAS', 'SANTIAGO DE PUPUJA', 'TIRAPATA'],
  'CARABAYA': ['MACUSANI', 'AJOYANI', 'AYAPATA', 'COASA', 'CORANI', 'CRUCERO', 'ITUATA', 'OLLACHEA', 'SAN GABÁN', 'USICAYOS'],
  'CHUCUITO': ['JULI', 'DESAGUADERO', 'HUACULLANI', 'KELLUYO', 'PISACOMA', 'POMATA', 'ZEPITA'],
  'EL COLLAO': ['ILAVE', 'CAPAZO', 'PILCUYO', 'SANTA ROSA', 'CONDURIRI'],
  'HUANCANÉ': ['HUANCANÉ', 'COJATA', 'HUATASANI', 'INCHUPALLA', 'PUSI', 'ROSASPATA', 'TARACO', 'VILQUE CHICO'],
  'LAMPA': ['LAMPA', 'CABANILLA', 'CALAPUJA', 'NICASIO', 'OCUVIRI', 'PALCA', 'PARATÍA', 'PUCARÁ', 'SANTA LUCÍA', 'VILAVILA'],
  'MELGAR': ['AYAVIRI', 'ANTAUTA', 'CUPI', 'LLALLI', 'MACARI', 'NUÑOA', 'ORURILLO', 'SANTA ROSA', 'UMACHIRI'],
  'MOHO': ['MOHO', 'CONIMA', 'HUAYRAPATA', 'TILALI'],
  'SAN ANTONIO DE PUTINA': ['PUTINA', 'ANANEA', 'PEDRO VILCA APAZA', 'QUILCAPUNCU', 'SINA'],
  'SAN ROMÁN': ['JULIACA', 'CABANA', 'CABANILLAS', 'CARACOTO'],
  'SANDIA': ['SANDIA', 'ALTO INAMBARI', 'CUYOCUYO', 'LIMBANI', 'PATAMBUCO', 'PHARA', 'QUIACA', 'SAN JUAN DEL ORO', 'YANAHUAYA', 'SAN PEDRO DE PUTINA PUNCO'],
  'YUNGUYO': ['YUNGUYO', 'ANAPIA', 'COPANI', 'CUTURAPI', 'OLLARAYA', 'TINICACHI', 'UNICACHI'],

  // SAN MARTÍN
  'MOYOBAMBA': ['MOYOBAMBA', 'CALZADA', 'HABANA', 'JEPELACIO', 'SORITOR', 'YANTALO'],
  'BELLAVISTA': ['BELLAVISTA', 'ALTO BIAVO', 'BAJO BIAVO', 'HUALLAGA', 'SAN PABLO', 'SAN RAFAEL'],
  'EL DORADO': ['SAN JOSÉ DE SISA', 'AGUA BLANCA', 'SAN MARTÍN', 'SANTA ROSA', 'SHATOJA'],
  'HUALLAGA': ['SAPOSOA', 'ALTO SAPOSOA', 'EL ESLABÓN', 'PISCOYACU', 'SACANCHE', 'TINGO DE SAPOSOA'],
  'LAMAS': ['LAMAS', 'ALONSO DE ALVARADO', 'BARRANQUITA', 'CAYNARACHI', 'CUÑUMBUQUI', 'PINTO RECODO', 'RUMISAPA', 'SAN ROQUE DE CUMBAZA', 'SHANAO', 'TABALOSOS', 'ZAPATERO'],
  'MARISCAL CÁCERES': ['JUANJUÍ', 'CAMPANILLA', 'HUICUNGO', 'PACHIZA', 'PAJARILLO'],
  'PICOTA': ['PICOTA', 'BUENOS AIRES', 'CASPIZAPA', 'LEONCIO PRADO', 'PILLUANA', 'PUCACACA', 'SAN CRISTÓBAL', 'SAN HILARIÓN', 'SHAMBOYACU', 'TINGO DE PONAZA', 'TRES UNIDOS'],
  'RIOJA': ['RIOJA', 'AWAJUN', 'ELÍAS SOPLIN VARGAS', 'NUEVA CAJAMARCA', 'PARDO MIGUEL', 'POSIC', 'SAN FERNANDO', 'YORONGOS', 'YURACYACU'],
  'SAN MARTÍN': ['TARAPOTO', 'ALBERTO LEVEAU', 'CACATACHI', 'CHAZUTA', 'CHIPURANA', 'EL PORVENIR', 'HUIMBAYOC', 'JUAN GUERRA', 'LA BANDA DE SHILCAYO', 'MORALES', 'PAPAPLAYA', 'SAN ANTONIO', 'SANTA CRUZ', 'SAUCE', 'SHAPAJA'],
  'TOCACHE': ['TOCACHE', 'NUEVO PROGRESO', 'PÓLVORA', 'SHUNTE', 'UCHIZA'],

  // TACNA
  'TACNA': ['TACNA', 'ALTO DE LA ALIANZA', 'CALANA', 'CIUDAD NUEVA', 'INCLÁN', 'PALCA', 'POCOLLAY', 'SAMA', 'CORONEL GREGORIO ALBARRACÍN LANCHIPA', 'PACHÍA'],
  'CANDARAVE': ['CANDARAVE', 'CAIRANI', 'CAMILACA', 'CURIBAYA', 'HUANUARA', 'QUILAHUANI'],
  'JORGE BASADRE': ['LOCUMBA', 'ILABAYA', 'ITE'],
  'TARATA': ['TARATA', 'CHUCATAMANI', 'ESTIQUE', 'ESTIQUE-PAMPA', 'SITAJARA', 'SUSAPAYA', 'TARUCACHI', 'TICACO'],

  // TUMBES
  'TUMBES': ['TUMBES', 'CORRALES', 'LA CRUZ', 'PAMPAS DE HOSPITAL', 'SAN JACINTO', 'SAN JUAN DE LA VIRGEN'],
  'CONTRALMIRANTE VILLAR': ['ZORRITOS', 'CASITAS', 'CANOAS DE PUNTA SAL'],
  'ZARUMILLA': ['ZARUMILLA', 'AGUAS VERDES', 'LA PALMA', 'MATAPALO'],

  // UCAYALI
  'CORONEL PORTILLO': ['CALLERÍA', 'CAMPO VERDE', 'IPARIA', 'MANANTAY', 'MASISEA', 'NUEVA REQUENA', 'YARINACOCHA'],
  'ATALAYA': ['RAYMONDI', 'SEPAHUA', 'TAHUANIA', 'YURÚA'],
  'PADRE ABAD': ['PADRE ABAD', 'IRAZOLA', 'CURIMANÁ', 'NESHUYA', 'ALEXANDER VON HUMBOLDT'],
  'PURÚS': ['PURÚS'],
};
